13-0 Add controllers first review
IgorMinkov/java-shareit pull request #1
Opened 2024-01-20 11:08 UTC by IgorMinkov

В этом спринте код проверяется коллекцией Постмана.
Покрытие тестами судя по всему будет в следующем спринте)

2024-01-21 09:59 UTC, Frilock requested changes
Добрый день, из комментариев:
не очень понял зачем делать мапперы спринговыми бинами, а также проверки наличия записи лучше сделать по другому

2024-01-21 09:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/Status.java
> +
Лишняя пустая строка

2024-01-21 09:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/handler/ErrorResponse.java
> +    public ErrorResponse(String error) {
Можно AllArgsConstructor

2024-01-21 09:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +@Component
А зачем делать маппер спринговым бином?  Можно просто методы статическими сделать

2024-01-21 09:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        if (item.getName() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2024-01-21 09:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                .filter(item -> item.getName().toLowerCase().contains(text.toLowerCase()))
Используйте StringUtils.containsIgnoreCase

2024-01-21 09:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                .filter(item -> item.getDescription().toLowerCase().contains(text.toLowerCase()))
Аналогично

2024-01-21 09:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        userRepository.getById(ownerId);
Так проверять наличие не принято, лучше сделайте метод приватный - existById или как то так

2024-01-22 08:32 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/booking/Status.java
> +
✓

2024-01-22 08:33 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/exception/handler/ErrorResponse.java
> +    public ErrorResponse(String error) {
✓

2024-01-22 08:41 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +@Component
✓

2024-01-22 09:07 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        if (item.getName() != null) {
✓
Внедрил, очень изящная конструкция вышла, к тому же надежнее.  спасибо за идею!

2024-01-22 10:03 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        userRepository.getById(ownerId);
✓

2024-01-22 10:09 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                .filter(item -> item.getName().toLowerCase().contains(text.toLowerCase()))
✓

2024-01-22 10:09 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                .filter(item -> item.getDescription().toLowerCase().contains(text.toLowerCase()))
✓

2024-01-22 16:50 UTC, Frilock approved these changes
Добрый вечер, принял, но 2 мелких комментария оставил

2024-01-22 16:50 UTC, Frilock commented on pom.xml
> +			<version>3.13.0</version>
Версию в пропертис

2024-01-22 16:50 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User user = repository.getById(id);
Зачем в переменную сохранять? Вы же ничего не возвращаете

2024-01-31 12:09 UTC, merged

2024-01-31 12:58 UTC, IgorMinkov commented on pom.xml
> +			<version>3.13.0</version>
✓

2024-01-31 12:58 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User user = repository.getById(id);
✓