Add bookings
IgorMinkov/java-shareit pull request #2
Opened 2024-02-10 21:32 UTC by IgorMinkov

Пул-реквест проверяется коллекцией тестов постмана.
Покрытие кода автотестами ждем в 15 спринте, коллеги уже делятся радостью)

2024-02-11 18:31 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    ) {
Скобку на предыдущую строку. Дальше не пишу такой комментарий

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                log.info("Пользователь {} реагирует на запрос вещи: {}", ownerId, bookingId);
Сьехало форматирование.

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +@AllArgsConstructor
Вообще лучше через билдер создавать обьект, но не принципиально

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Table(name = "bookings", schema = "public")
schema = "public" - значение по умолчанию, можно не указывать

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Будьте аккуратней при использовании Data над классом Entity https://habr.com/ru/companies/haulmont/articles/564682/

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/State.java
> +
Пропуски лишние

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/State.java
> +
Лишний пропуск

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +@Repository
Смотрите, над интерфейсами нет смысла ставить аннотации помечающих класс бином, главное чтоб аннотация стояла над реализацией данного интерфейса.

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Item item = itemService.getById(itemId, userId);
Вот тут странно, вы же внутри checkUser(userId); уже делаете запрос по id?
и почему getById принимает 2 параметра? Лучше название метода сменить

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        checkBooking(bookingId);
Аналогично

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/ItemOutDto.java
> +    public ItemOutDto(Long id, String name, String description, Boolean available) {
RequiredArgsConstructor =) На ваше усмотрение

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Table(name = "comments", schema = "public")
Аналогично

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@EqualsAndHashCode(of = {"id"})
Мне не нравиться подход, когда вы equals генерируете только по идентификатору, это не совсем верно.

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @Column(name = "text", nullable = false)
В данной аннотации для строковых полей также лучше задавать размерность поля которую вы указываете в скрипте, чтобы лишний раз туда не лазить

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    public Comment(String text) {
А зачем такой конструктор? как то не очень выглядит

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +@Repository
Анналогично

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +@Repository
Анналогично

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +@Repository
Анналогично

2024-02-11 18:31 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        boolean check = repository.findByEmail(email).stream()
Лучше как то так - isValidateEmail, или что то вроде

2024-02-11 18:31 UTC, Frilock commented on src/main/resources/schema.sql
> +    name VARCHAR(127) NOT NULL,
Данные размеры полей лучше указывать в Column тоже

2024-02-11 19:10 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    ) {
✓

2024-02-11 19:11 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                log.info("Пользователь {} реагирует на запрос вещи: {}", ownerId, bookingId);
✓

2024-02-11 19:13 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Table(name = "bookings", schema = "public")
✓

2024-02-11 19:14 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/booking/model/State.java
> +
✓

2024-02-11 19:14 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/booking/model/State.java
> +
✓

2024-02-11 19:16 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +@Repository
✓

2024-02-11 19:30 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @Column(name = "text", nullable = false)
✓

2024-02-11 19:31 UTC, IgorMinkov commented on src/main/resources/schema.sql
> +    name VARCHAR(127) NOT NULL,
✓

2024-02-11 20:25 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +@AllArgsConstructor
✓

2024-02-11 20:27 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/item/dto/ItemOutDto.java
> +    public ItemOutDto(Long id, String name, String description, Boolean available) {
✓ внедрил Builder, отпала необходимость в RequiredArgsConstructor :)

2024-02-11 20:27 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Table(name = "comments", schema = "public")
✓

2024-02-11 20:28 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    public Comment(String text) {
✓ вылечено билдером

2024-02-11 20:28 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +@Repository
✓

2024-02-11 20:28 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +@Repository
✓

2024-02-11 20:29 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +@Repository
✓

2024-02-11 20:56 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
✓ Статья огонь, спасибо!
Добавлены аннотации к полям классов-моделей, где участвуют User и Item:
@ToString.Exclude
@EqualsAndHashCode.Exclude

2024-02-11 20:58 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@EqualsAndHashCode(of = {"id"})
✓
Исправлено вместе с пунктом со ссылкой на статью на Хабре.
Добавлены аннотации:
@ToString.Exclude
@EqualsAndHashCode.Exclude

2024-02-11 21:09 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        boolean check = repository.findByEmail(email).stream()
✓
Конкретизировал название метода - isEmailUnique()

2024-02-11 21:17 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        checkBooking(bookingId);
✓

2024-02-11 21:47 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Item item = itemService.getById(itemId, userId);
✓
1. Удалил второй параметр из getById - нет в нем необходимости.
2. Развязал проверку и получение Item и User - убрал проверку из получения, получается дублировалась суть. Теперь check() используется там, где не происходит getById.
3. В BookingService метод check() заменен на getById(Long bookingId) в соответствии с концепцией из пункта 2 - не нужна проверка без получения сущности.

2024-02-11 21:48 UTC, IgorMinkov commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
UPD: отметил улучшение быстродействия программы!
Даже на таком сравнительно небольшом коде тесты после внедрения правки пошли быстрее, заметно невооруженным глазом.

2024-02-12 17:33 UTC, Frilock approved these changes
Принято

2024-02-12 17:33 UTC, Frilock commented on pom.xml
> +			<version>20.1.0</version>
Версию в пропертис

2024-02-12 18:05 UTC, merged

2024-02-18 14:01 UTC, IgorMinkov commented on pom.xml
> +			<version>20.1.0</version>
✓